// Mocks generated by Mockito 5.4.4 from annotations
// in carmen_garden_pos/test/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;

import 'package:carmen_garden_pos/data/datasources/local/inventory_dao.dart'
    as _i16;
import 'package:carmen_garden_pos/data/datasources/local/order_dao.dart'
    as _i14;
import 'package:carmen_garden_pos/data/datasources/local/payment_dao.dart'
    as _i15;
import 'package:carmen_garden_pos/models/activity_log.dart' as _i11;
import 'package:carmen_garden_pos/models/inventory.dart' as _i10;
import 'package:carmen_garden_pos/models/order.dart' as _i8;
import 'package:carmen_garden_pos/models/payment.dart' as _i9;
import 'package:carmen_garden_pos/services/activity_log_service.dart' as _i17;
import 'package:carmen_garden_pos/services/connectivity_service.dart' as _i19;
import 'package:dio/src/adapter.dart' as _i3;
import 'package:dio/src/cancel_token.dart' as _i13;
import 'package:dio/src/dio.dart' as _i7;
import 'package:dio/src/dio_mixin.dart' as _i5;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_1 extends _i1.SmartFake
    implements _i3.HttpClientAdapter {
  _FakeHttpClientAdapter_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_2 extends _i1.SmartFake implements _i4.Transformer {
  _FakeTransformer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_3 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrder_6 extends _i1.SmartFake implements _i8.Order {
  _FakeOrder_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayment_7 extends _i1.SmartFake implements _i9.Payment {
  _FakePayment_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInventory_8 extends _i1.SmartFake implements _i10.Inventory {
  _FakeInventory_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInventoryTransaction_9 extends _i1.SmartFake
    implements _i10.InventoryTransaction {
  _FakeInventoryTransaction_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeActivityLog_10 extends _i1.SmartFake implements _i11.ActivityLog {
  _FakeActivityLog_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_0(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.BaseOptions);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_1(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i3.HttpClientAdapter);

  @override
  set httpClientAdapter(_i3.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_2(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i4.Transformer);

  @override
  set transformer(_i4.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_3(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i5.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i13.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i13.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = r'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i12.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<dynamic>>);

  @override
  _i12.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i13.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = r'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i12.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<dynamic>>);

  @override
  _i12.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i13.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i13.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i12.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i12.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i12.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i5.Interceptors? interceptors,
    _i3.HttpClientAdapter? httpClientAdapter,
    _i4.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
          {
            #options: options,
            #interceptors: interceptors,
            #httpClientAdapter: httpClientAdapter,
            #transformer: transformer,
          },
        ),
        returnValue: _FakeDio_5(
          this,
          Invocation.method(
            #clone,
            [],
            {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            },
          ),
        ),
      ) as _i7.Dio);
}

/// A class which mocks [OrderDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderDao extends _i1.Mock implements _i14.OrderDao {
  MockOrderDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i8.Order> createOrder(_i8.Order? order) => (super.noSuchMethod(
        Invocation.method(
          #createOrder,
          [order],
        ),
        returnValue: _i12.Future<_i8.Order>.value(_FakeOrder_6(
          this,
          Invocation.method(
            #createOrder,
            [order],
          ),
        )),
      ) as _i12.Future<_i8.Order>);

  @override
  _i12.Future<void> restoreOrder(_i8.Order? order) => (super.noSuchMethod(
        Invocation.method(
          #restoreOrder,
          [order],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i8.Order?> getOrderById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOrderById,
          [id],
        ),
        returnValue: _i12.Future<_i8.Order?>.value(),
      ) as _i12.Future<_i8.Order?>);

  @override
  _i12.Future<List<_i8.Order>> getOrders({
    _i8.OrderStatus? status,
    DateTime? fromDate,
    DateTime? toDate,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrders,
          [],
          {
            #status: status,
            #fromDate: fromDate,
            #toDate: toDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i12.Future<List<_i8.Order>>.value(<_i8.Order>[]),
      ) as _i12.Future<List<_i8.Order>>);

  @override
  _i12.Future<List<_i8.Order>> getTodaysOrders() => (super.noSuchMethod(
        Invocation.method(
          #getTodaysOrders,
          [],
        ),
        returnValue: _i12.Future<List<_i8.Order>>.value(<_i8.Order>[]),
      ) as _i12.Future<List<_i8.Order>>);

  @override
  _i12.Future<void> updateOrderStatus(
    String? id,
    _i8.OrderStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<void> deleteOrder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteOrder,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<List<_i8.Order>> getUnsyncedOrders() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedOrders,
          [],
        ),
        returnValue: _i12.Future<List<_i8.Order>>.value(<_i8.Order>[]),
      ) as _i12.Future<List<_i8.Order>>);

  @override
  _i12.Future<void> markAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<Map<_i8.OrderStatus, int>> getOrderCountByStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderCountByStatus,
          [],
        ),
        returnValue: _i12.Future<Map<_i8.OrderStatus, int>>.value(
            <_i8.OrderStatus, int>{}),
      ) as _i12.Future<Map<_i8.OrderStatus, int>>);
}

/// A class which mocks [PaymentDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentDao extends _i1.Mock implements _i15.PaymentDao {
  MockPaymentDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i9.Payment> createPayment(_i9.Payment? payment) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPayment,
          [payment],
        ),
        returnValue: _i12.Future<_i9.Payment>.value(_FakePayment_7(
          this,
          Invocation.method(
            #createPayment,
            [payment],
          ),
        )),
      ) as _i12.Future<_i9.Payment>);

  @override
  _i12.Future<_i9.Payment?> getPaymentByOrderId(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentByOrderId,
          [orderId],
        ),
        returnValue: _i12.Future<_i9.Payment?>.value(),
      ) as _i12.Future<_i9.Payment?>);

  @override
  _i12.Future<List<_i9.Payment>> getPayments({
    DateTime? fromDate,
    DateTime? toDate,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPayments,
          [],
          {
            #fromDate: fromDate,
            #toDate: toDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i12.Future<List<_i9.Payment>>.value(<_i9.Payment>[]),
      ) as _i12.Future<List<_i9.Payment>>);

  @override
  _i12.Future<double> getTodaysTotalCash() => (super.noSuchMethod(
        Invocation.method(
          #getTodaysTotalCash,
          [],
        ),
        returnValue: _i12.Future<double>.value(0.0),
      ) as _i12.Future<double>);

  @override
  _i12.Future<double> getTotalSales({
    required DateTime? fromDate,
    required DateTime? toDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalSales,
          [],
          {
            #fromDate: fromDate,
            #toDate: toDate,
          },
        ),
        returnValue: _i12.Future<double>.value(0.0),
      ) as _i12.Future<double>);

  @override
  _i12.Future<List<_i9.Payment>> getUnsyncedPayments() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedPayments,
          [],
        ),
        returnValue: _i12.Future<List<_i9.Payment>>.value(<_i9.Payment>[]),
      ) as _i12.Future<List<_i9.Payment>>);

  @override
  _i12.Future<void> markAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [InventoryDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryDao extends _i1.Mock implements _i16.InventoryDao {
  MockInventoryDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i10.Inventory> getOrCreateInventory(String? menuItemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateInventory,
          [menuItemId],
        ),
        returnValue: _i12.Future<_i10.Inventory>.value(_FakeInventory_8(
          this,
          Invocation.method(
            #getOrCreateInventory,
            [menuItemId],
          ),
        )),
      ) as _i12.Future<_i10.Inventory>);

  @override
  _i12.Future<List<_i10.Inventory>> getAllInventory() => (super.noSuchMethod(
        Invocation.method(
          #getAllInventory,
          [],
        ),
        returnValue:
            _i12.Future<List<_i10.Inventory>>.value(<_i10.Inventory>[]),
      ) as _i12.Future<List<_i10.Inventory>>);

  @override
  _i12.Future<List<_i10.Inventory>> getLowStockItems() => (super.noSuchMethod(
        Invocation.method(
          #getLowStockItems,
          [],
        ),
        returnValue:
            _i12.Future<List<_i10.Inventory>>.value(<_i10.Inventory>[]),
      ) as _i12.Future<List<_i10.Inventory>>);

  @override
  _i12.Future<_i10.Inventory> updateStock({
    required String? menuItemId,
    required int? newStock,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStock,
          [],
          {
            #menuItemId: menuItemId,
            #newStock: newStock,
          },
        ),
        returnValue: _i12.Future<_i10.Inventory>.value(_FakeInventory_8(
          this,
          Invocation.method(
            #updateStock,
            [],
            {
              #menuItemId: menuItemId,
              #newStock: newStock,
            },
          ),
        )),
      ) as _i12.Future<_i10.Inventory>);

  @override
  _i12.Future<_i10.Inventory> adjustStock({
    required String? menuItemId,
    required int? adjustment,
    required _i10.InventoryAdjustmentReason? reason,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #adjustStock,
          [],
          {
            #menuItemId: menuItemId,
            #adjustment: adjustment,
            #reason: reason,
            #notes: notes,
          },
        ),
        returnValue: _i12.Future<_i10.Inventory>.value(_FakeInventory_8(
          this,
          Invocation.method(
            #adjustStock,
            [],
            {
              #menuItemId: menuItemId,
              #adjustment: adjustment,
              #reason: reason,
              #notes: notes,
            },
          ),
        )),
      ) as _i12.Future<_i10.Inventory>);

  @override
  _i12.Future<_i10.InventoryTransaction> createTransaction(
          _i10.InventoryTransaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransaction,
          [transaction],
        ),
        returnValue: _i12.Future<_i10.InventoryTransaction>.value(
            _FakeInventoryTransaction_9(
          this,
          Invocation.method(
            #createTransaction,
            [transaction],
          ),
        )),
      ) as _i12.Future<_i10.InventoryTransaction>);

  @override
  _i12.Future<List<_i10.InventoryTransaction>> getTransactions({
    required String? inventoryId,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [],
          {
            #inventoryId: inventoryId,
            #limit: limit,
          },
        ),
        returnValue: _i12.Future<List<_i10.InventoryTransaction>>.value(
            <_i10.InventoryTransaction>[]),
      ) as _i12.Future<List<_i10.InventoryTransaction>>);

  @override
  _i12.Future<List<_i10.InventoryTransaction>> getUnsyncedTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedTransactions,
          [],
        ),
        returnValue: _i12.Future<List<_i10.InventoryTransaction>>.value(
            <_i10.InventoryTransaction>[]),
      ) as _i12.Future<List<_i10.InventoryTransaction>>);

  @override
  _i12.Future<void> markTransactionAsSynced(String? id) => (super.noSuchMethod(
        Invocation.method(
          #markTransactionAsSynced,
          [id],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [ActivityLogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivityLogService extends _i1.Mock
    implements _i17.ActivityLogService {
  MockActivityLogService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i11.ActivityLog> logEvent({
    required _i11.ActivityEventType? eventType,
    required _i11.ActivityEntityType? entityType,
    String? entityId,
    required String? description,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEvent,
          [],
          {
            #eventType: eventType,
            #entityType: entityType,
            #entityId: entityId,
            #description: description,
            #metadata: metadata,
          },
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logEvent,
            [],
            {
              #eventType: eventType,
              #entityType: entityType,
              #entityId: entityId,
              #description: description,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logOrderCreated(
    String? orderId,
    int? orderNumber,
    double? total,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logOrderCreated,
          [
            orderId,
            orderNumber,
            total,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logOrderCreated,
            [
              orderId,
              orderNumber,
              total,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logOrderUpdated(
    String? orderId,
    int? orderNumber,
    String? changes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logOrderUpdated,
          [
            orderId,
            orderNumber,
            changes,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logOrderUpdated,
            [
              orderId,
              orderNumber,
              changes,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logOrderStatusChanged(
    String? orderId,
    int? orderNumber,
    String? oldStatus,
    String? newStatus,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logOrderStatusChanged,
          [
            orderId,
            orderNumber,
            oldStatus,
            newStatus,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logOrderStatusChanged,
            [
              orderId,
              orderNumber,
              oldStatus,
              newStatus,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logOrderCompleted(
    String? orderId,
    int? orderNumber,
    double? total,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logOrderCompleted,
          [
            orderId,
            orderNumber,
            total,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logOrderCompleted,
            [
              orderId,
              orderNumber,
              total,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logOrderCancelled(
    String? orderId,
    int? orderNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logOrderCancelled,
          [
            orderId,
            orderNumber,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logOrderCancelled,
            [
              orderId,
              orderNumber,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logOrderDeleted(
    String? orderId,
    int? orderNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logOrderDeleted,
          [
            orderId,
            orderNumber,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logOrderDeleted,
            [
              orderId,
              orderNumber,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logPaymentProcessed(
    String? paymentId,
    int? orderNumber,
    double? amount,
    double? change,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logPaymentProcessed,
          [
            paymentId,
            orderNumber,
            amount,
            change,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logPaymentProcessed,
            [
              paymentId,
              orderNumber,
              amount,
              change,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logPaymentRefunded(
    String? paymentId,
    int? orderNumber,
    double? amount,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logPaymentRefunded,
          [
            paymentId,
            orderNumber,
            amount,
            reason,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logPaymentRefunded,
            [
              paymentId,
              orderNumber,
              amount,
              reason,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logInventoryAdjusted(
    String? itemName,
    int? adjustment,
    String? reason,
    int? newStock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logInventoryAdjusted,
          [
            itemName,
            adjustment,
            reason,
            newStock,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logInventoryAdjusted,
            [
              itemName,
              adjustment,
              reason,
              newStock,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logItemAdded(
    String? itemName,
    String? category,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logItemAdded,
          [
            itemName,
            category,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logItemAdded,
            [
              itemName,
              category,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logItemUpdated(
    String? itemName,
    String? changes,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logItemUpdated,
          [
            itemName,
            changes,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logItemUpdated,
            [
              itemName,
              changes,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logItemDeleted(String? itemName) =>
      (super.noSuchMethod(
        Invocation.method(
          #logItemDeleted,
          [itemName],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logItemDeleted,
            [itemName],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logInventoryRestocked(
    String? itemName,
    int? quantity,
    int? newStock,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logInventoryRestocked,
          [
            itemName,
            quantity,
            newStock,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logInventoryRestocked,
            [
              itemName,
              quantity,
              newStock,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logSyncCompleted(int? recordCount) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSyncCompleted,
          [recordCount],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logSyncCompleted,
            [recordCount],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logSyncFailed(String? error) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSyncFailed,
          [error],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logSyncFailed,
            [error],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logDataExported(
    String? exportType,
    int? recordCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDataExported,
          [
            exportType,
            recordCount,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logDataExported,
            [
              exportType,
              recordCount,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<_i11.ActivityLog> logMenuSynced(
    int? categoryCount,
    int? itemCount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #logMenuSynced,
          [
            categoryCount,
            itemCount,
          ],
        ),
        returnValue: _i12.Future<_i11.ActivityLog>.value(_FakeActivityLog_10(
          this,
          Invocation.method(
            #logMenuSynced,
            [
              categoryCount,
              itemCount,
            ],
          ),
        )),
      ) as _i12.Future<_i11.ActivityLog>);

  @override
  _i12.Future<List<_i11.ActivityLog>> getLogs({
    _i11.ActivityEventType? eventType,
    _i11.ActivityEntityType? entityType,
    DateTime? fromDate,
    DateTime? toDate,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLogs,
          [],
          {
            #eventType: eventType,
            #entityType: entityType,
            #fromDate: fromDate,
            #toDate: toDate,
            #limit: limit,
          },
        ),
        returnValue:
            _i12.Future<List<_i11.ActivityLog>>.value(<_i11.ActivityLog>[]),
      ) as _i12.Future<List<_i11.ActivityLog>>);

  @override
  _i12.Future<List<_i11.ActivityLog>> getTodaysLogs() => (super.noSuchMethod(
        Invocation.method(
          #getTodaysLogs,
          [],
        ),
        returnValue:
            _i12.Future<List<_i11.ActivityLog>>.value(<_i11.ActivityLog>[]),
      ) as _i12.Future<List<_i11.ActivityLog>>);

  @override
  _i12.Future<Map<_i11.ActivityEventType, int>> getEventCounts({
    DateTime? fromDate,
    DateTime? toDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventCounts,
          [],
          {
            #fromDate: fromDate,
            #toDate: toDate,
          },
        ),
        returnValue: _i12.Future<Map<_i11.ActivityEventType, int>>.value(
            <_i11.ActivityEventType, int>{}),
      ) as _i12.Future<Map<_i11.ActivityEventType, int>>);

  @override
  _i12.Future<String> exportToCsv({
    DateTime? fromDate,
    DateTime? toDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToCsv,
          [],
          {
            #fromDate: fromDate,
            #toDate: toDate,
          },
        ),
        returnValue: _i12.Future<String>.value(_i18.dummyValue<String>(
          this,
          Invocation.method(
            #exportToCsv,
            [],
            {
              #fromDate: fromDate,
              #toDate: toDate,
            },
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<int> cleanupOldLogs() => (super.noSuchMethod(
        Invocation.method(
          #cleanupOldLogs,
          [],
        ),
        returnValue: _i12.Future<int>.value(0),
      ) as _i12.Future<int>);

  @override
  _i12.Future<List<_i11.ActivityLog>> getUnsyncedLogs() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedLogs,
          [],
        ),
        returnValue:
            _i12.Future<List<_i11.ActivityLog>>.value(<_i11.ActivityLog>[]),
      ) as _i12.Future<List<_i11.ActivityLog>>);

  @override
  _i12.Future<void> markAsSynced(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [ids],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i19.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<_i19.ConnectivityStatus> get statusStream => (super.noSuchMethod(
        Invocation.getter(#statusStream),
        returnValue: _i12.Stream<_i19.ConnectivityStatus>.empty(),
      ) as _i12.Stream<_i19.ConnectivityStatus>);

  @override
  _i19.ConnectivityStatus get currentStatus => (super.noSuchMethod(
        Invocation.getter(#currentStatus),
        returnValue: _i19.ConnectivityStatus.online,
      ) as _i19.ConnectivityStatus);

  @override
  bool get isOnline => (super.noSuchMethod(
        Invocation.getter(#isOnline),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  _i12.Future<_i19.ConnectivityStatus> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i12.Future<_i19.ConnectivityStatus>.value(
            _i19.ConnectivityStatus.online),
      ) as _i12.Future<_i19.ConnectivityStatus>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
