// Mocks generated by Mockito 5.4.4 from annotations
// in carmen_garden_pos/test/ui/pos_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:carmen_garden_pos/data/datasources/local/menu_dao.dart' as _i4;
import 'package:carmen_garden_pos/models/category.dart' as _i2;
import 'package:carmen_garden_pos/models/menu_item.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategory_0 extends _i1.SmartFake implements _i2.Category {
  _FakeCategory_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMenuItem_1 extends _i1.SmartFake implements _i3.MenuItem {
  _FakeMenuItem_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeItemModifier_2 extends _i1.SmartFake implements _i3.ItemModifier {
  _FakeItemModifier_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MenuDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockMenuDao extends _i1.Mock implements _i4.MenuDao {
  MockMenuDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Category> createCategory(_i2.Category? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [category],
        ),
        returnValue: _i5.Future<_i2.Category>.value(_FakeCategory_0(
          this,
          Invocation.method(
            #createCategory,
            [category],
          ),
        )),
      ) as _i5.Future<_i2.Category>);

  @override
  _i5.Future<List<_i2.Category>> getCategories({bool? activeOnly = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
          {#activeOnly: activeOnly},
        ),
        returnValue: _i5.Future<List<_i2.Category>>.value(<_i2.Category>[]),
      ) as _i5.Future<List<_i2.Category>>);

  @override
  _i5.Future<_i3.MenuItem> createMenuItem(_i3.MenuItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMenuItem,
          [item],
        ),
        returnValue: _i5.Future<_i3.MenuItem>.value(_FakeMenuItem_1(
          this,
          Invocation.method(
            #createMenuItem,
            [item],
          ),
        )),
      ) as _i5.Future<_i3.MenuItem>);

  @override
  _i5.Future<List<_i3.MenuItem>> getMenuItems({
    String? categoryId,
    bool? availableOnly = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMenuItems,
          [],
          {
            #categoryId: categoryId,
            #availableOnly: availableOnly,
          },
        ),
        returnValue: _i5.Future<List<_i3.MenuItem>>.value(<_i3.MenuItem>[]),
      ) as _i5.Future<List<_i3.MenuItem>>);

  @override
  _i5.Future<_i3.MenuItem?> getMenuItemById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMenuItemById,
          [id],
        ),
        returnValue: _i5.Future<_i3.MenuItem?>.value(),
      ) as _i5.Future<_i3.MenuItem?>);

  @override
  _i5.Future<void> setItemAvailability(
    String? id,
    bool? isAvailable,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setItemAvailability,
          [
            id,
            isAvailable,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.MenuItem> updateMenuItem(_i3.MenuItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMenuItem,
          [item],
        ),
        returnValue: _i5.Future<_i3.MenuItem>.value(_FakeMenuItem_1(
          this,
          Invocation.method(
            #updateMenuItem,
            [item],
          ),
        )),
      ) as _i5.Future<_i3.MenuItem>);

  @override
  _i5.Future<void> deleteMenuItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMenuItem,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.ItemModifier>> getModifiersForItem(String? menuItemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModifiersForItem,
          [menuItemId],
        ),
        returnValue:
            _i5.Future<List<_i3.ItemModifier>>.value(<_i3.ItemModifier>[]),
      ) as _i5.Future<List<_i3.ItemModifier>>);

  @override
  _i5.Future<_i3.ItemModifier> createModifier(_i3.ItemModifier? modifier) =>
      (super.noSuchMethod(
        Invocation.method(
          #createModifier,
          [modifier],
        ),
        returnValue: _i5.Future<_i3.ItemModifier>.value(_FakeItemModifier_2(
          this,
          Invocation.method(
            #createModifier,
            [modifier],
          ),
        )),
      ) as _i5.Future<_i3.ItemModifier>);

  @override
  _i5.Future<_i3.ItemModifier> updateModifier(_i3.ItemModifier? modifier) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateModifier,
          [modifier],
        ),
        returnValue: _i5.Future<_i3.ItemModifier>.value(_FakeItemModifier_2(
          this,
          Invocation.method(
            #updateModifier,
            [modifier],
          ),
        )),
      ) as _i5.Future<_i3.ItemModifier>);

  @override
  _i5.Future<void> deleteModifier(String? modifierId) => (super.noSuchMethod(
        Invocation.method(
          #deleteModifier,
          [modifierId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteModifiersForItem(String? menuItemId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteModifiersForItem,
          [menuItemId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> replaceAllMenuData({
    required List<_i2.Category>? categories,
    required List<_i3.MenuItem>? items,
    required List<_i3.ItemModifier>? modifiers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceAllMenuData,
          [],
          {
            #categories: categories,
            #items: items,
            #modifiers: modifiers,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
